### ISSUE TITLE
npm start 出错

### ISSUE THREAD

**Issue by amio** [ic4/drops#3]
安装完依赖之后启动不起来：

```
> c14m@0.0.1 start /Users/amio/git/c14m
> node ./bin/www


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at Function.app.listen (/Users/amio/git/c14m/node_modules/express/lib/application.js:531:24)
    at Object.<anonymous> (/Users/amio/git/c14m/bin/www:7:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by nyanhan** [comment]
是不是 3000 端口被占用了， 要不我换个端口？

**Comment by amio** [comment]
果然，忘记我还开着pm2了在后台悄悄跑着 ＝ ＝
不用改，我的问题
